package housekeeper.entities;
// Generated 2017-12-9 17:20:53 by Hibernate Tools 5.2.5.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CardQuery generated by hbm2java
 */
@Entity
@Table(name="CardQuery"
    ,catalog="GuanJiapo"
)
public class CardQuery  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2573619991671317203L;
	private CardQueryId id;

    public CardQuery() {
    }

    public CardQuery(CardQueryId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cardId", column=@Column(name="CARD_ID", nullable=false) ), 
        @AttributeOverride(name="cardName", column=@Column(name="CARD_NAME") ), 
        @AttributeOverride(name="cardNumber", column=@Column(name="CARD_NUMBER") ), 
        @AttributeOverride(name="money", column=@Column(name="MONEY", precision=22, scale=0) ), 
        @AttributeOverride(name="remark", column=@Column(name="REMARK") ), 
        @AttributeOverride(name="memberId", column=@Column(name="MEMBER_ID", nullable=false) ) } )
    public CardQueryId getId() {
        return this.id;
    }
    
    public void setId(CardQueryId id) {
        this.id = id;
    }




}


