package housekeeper.entities;
// Generated 2017-12-9 21:16:03 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CashInQueryId generated by hbm2java
 */
@Embeddable
public class CashInQueryId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4021854440705842796L;
	private int cashinId;
	private Date time;
	private String site;
	private String people;
	private Double money;
	private String remark;
	private Integer memberId;
	private Integer itemId;
	private Integer subitemId;
	private Integer accountId;
	private String itemName;
	private String subitemName;
	private String accountName;

	public CashInQueryId() {
	}

	public CashInQueryId(int cashinId) {
		this.cashinId = cashinId;
	}

	public CashInQueryId(int cashinId, Date time, String site, String people, Double money, String remark,
			Integer memberId, Integer itemId, Integer subitemId, Integer accountId, String itemName, String subitemName,
			String accountName) {
		this.cashinId = cashinId;
		this.time = time;
		this.site = site;
		this.people = people;
		this.money = money;
		this.remark = remark;
		this.memberId = memberId;
		this.itemId = itemId;
		this.subitemId = subitemId;
		this.accountId = accountId;
		this.itemName = itemName;
		this.subitemName = subitemName;
		this.accountName = accountName;
	}

	@Column(name = "CASHIN_ID", nullable = false)
	public int getCashinId() {
		return this.cashinId;
	}

	public void setCashinId(int cashinId) {
		this.cashinId = cashinId;
	}

	@Column(name = "TIME", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "SITE")
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "PEOPLE")
	public String getPeople() {
		return this.people;
	}

	public void setPeople(String people) {
		this.people = people;
	}

	@Column(name = "MONEY", precision = 22, scale = 0)
	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "MEMBER_ID")
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@Column(name = "ITEM_ID")
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@Column(name = "SUBITEM_ID")
	public Integer getSubitemId() {
		return this.subitemId;
	}

	public void setSubitemId(Integer subitemId) {
		this.subitemId = subitemId;
	}

	@Column(name = "ACCOUNT_ID")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@Column(name = "ITEM_NAME")
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "SUBITEM_NAME")
	public String getSubitemName() {
		return this.subitemName;
	}

	public void setSubitemName(String subitemName) {
		this.subitemName = subitemName;
	}

	@Column(name = "ACCOUNT_NAME")
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CashInQueryId))
			return false;
		CashInQueryId castOther = (CashInQueryId) other;

		return (this.getCashinId() == castOther.getCashinId())
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
						&& this.getTime().equals(castOther.getTime())))
				&& ((this.getSite() == castOther.getSite()) || (this.getSite() != null && castOther.getSite() != null
						&& this.getSite().equals(castOther.getSite())))
				&& ((this.getPeople() == castOther.getPeople()) || (this.getPeople() != null
						&& castOther.getPeople() != null && this.getPeople().equals(castOther.getPeople())))
				&& ((this.getMoney() == castOther.getMoney()) || (this.getMoney() != null
						&& castOther.getMoney() != null && this.getMoney().equals(castOther.getMoney())))
				&& ((this.getRemark() == castOther.getRemark()) || (this.getRemark() != null
						&& castOther.getRemark() != null && this.getRemark().equals(castOther.getRemark())))
				&& ((this.getMemberId() == castOther.getMemberId()) || (this.getMemberId() != null
						&& castOther.getMemberId() != null && this.getMemberId().equals(castOther.getMemberId())))
				&& ((this.getItemId() == castOther.getItemId()) || (this.getItemId() != null
						&& castOther.getItemId() != null && this.getItemId().equals(castOther.getItemId())))
				&& ((this.getSubitemId() == castOther.getSubitemId()) || (this.getSubitemId() != null
						&& castOther.getSubitemId() != null && this.getSubitemId().equals(castOther.getSubitemId())))
				&& ((this.getAccountId() == castOther.getAccountId()) || (this.getAccountId() != null
						&& castOther.getAccountId() != null && this.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getItemName() == castOther.getItemName()) || (this.getItemName() != null
						&& castOther.getItemName() != null && this.getItemName().equals(castOther.getItemName())))
				&& ((this.getSubitemName() == castOther.getSubitemName())
						|| (this.getSubitemName() != null && castOther.getSubitemName() != null
								&& this.getSubitemName().equals(castOther.getSubitemName())))
				&& ((this.getAccountName() == castOther.getAccountName())
						|| (this.getAccountName() != null && castOther.getAccountName() != null
								&& this.getAccountName().equals(castOther.getAccountName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCashinId();
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		result = 37 * result + (getSite() == null ? 0 : this.getSite().hashCode());
		result = 37 * result + (getPeople() == null ? 0 : this.getPeople().hashCode());
		result = 37 * result + (getMoney() == null ? 0 : this.getMoney().hashCode());
		result = 37 * result + (getRemark() == null ? 0 : this.getRemark().hashCode());
		result = 37 * result + (getMemberId() == null ? 0 : this.getMemberId().hashCode());
		result = 37 * result + (getItemId() == null ? 0 : this.getItemId().hashCode());
		result = 37 * result + (getSubitemId() == null ? 0 : this.getSubitemId().hashCode());
		result = 37 * result + (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result + (getItemName() == null ? 0 : this.getItemName().hashCode());
		result = 37 * result + (getSubitemName() == null ? 0 : this.getSubitemName().hashCode());
		result = 37 * result + (getAccountName() == null ? 0 : this.getAccountName().hashCode());
		return result;
	}

}
