package housekeeper.entities;
// Generated 2017-12-9 16:05:59 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SubItemQuery generated by hbm2java
 */
@Entity
@Table(name = "SubItemQuery", catalog = "GuanJiapo")
public class SubItemQuery implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6191161460665818238L;
	private SubItemQueryId id;

	public SubItemQuery() {
	}

	public SubItemQuery(SubItemQueryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemId", column = @Column(name = "ITEM_ID", nullable = false)),
			@AttributeOverride(name = "subitemId", column = @Column(name = "SUBITEM_ID", nullable = false)),
			@AttributeOverride(name = "subitemName", column = @Column(name = "SUBITEM_NAME")) })
	public SubItemQueryId getId() {
		return this.id;
	}

	public void setId(SubItemQueryId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "SubItemQuery [id=" + id + "]";
	}

}
